
### CIM Compliant Data Sources ##
[monitor:///home/export/data/csv-export/ready/OMNIS.flow-dns*.csv.gz]
disabled = false
index = netscoutoais
sourcetype = netscout:omnis:flow:dns

[monitor:///home/export/data/csv-export/ready/OMNIS.flow-http*.csv.gz]
disabled = false
index = netscoutoais
sourcetype = netscout:omnis:flow:http

[monitor:///home/export/data/csv-export/ready/OMNIS.flow-https*.csv.gz]
disabled = false
index = netscoutoais
sourcetype = netscout:omnis:flow:https

[monitor:///home/export/data/csv-export/ready/OMNIS.flow-icmp*.csv.gz]
disabled = false
index = netscoutoais
sourcetype = netscout:omnis:flow:icmp

[monitor:///home/export/data/csv-export/ready/OMNIS.flow-smb*.csv.gz]
disabled = false
index = netscoutoais
sourcetype = netscout:omnis:flow:smb


### Other Data Sources
[monitor:///home/export/data/csv-export/ready/OMNIS.netops*.csv.gz]
disabled = false
index = netscoutoais
sourcetype = netscout:omnis:flow:netops

[monitor:///home/export/data/csv-export/ready/OMNIS.application*.csv.gz]
disabled = false
index = netscoutoais
sourcetype = netscout:omnis:flow:application

[monitor:///home/export/data/csv-export/ready/OMNIS.asset*.csv.gz]
disabled = false
index = netscoutoais
sourcetype = netscout:omnis:flow:asset

[monitor:///home/export/data/csv-export/ready/OMNIS.sre*.csv.gz]
disabled = false
index = netscoutoais
sourcetype = netscout:omnis:flow:sre

[monitor:///home/export/data/csv-export/ready/OMNIS.uc*.csv.gz]
disabled = false
index = netscoutoais
sourcetype = netscout:omnis:flow:uc

[monitor:///home/export/data/csv-export/ready/OMNIS.flow-base*.csv.gz]
disabled = false
index = netscoutoais
sourcetype = netscout:omnis:flow:base
crcSalt = <SOURCE>