[header_drop]
REGEX = ^timestamp
DEST_KEY = queue
FORMAT = nullQueue


[netscout_dns_header]
DELIMS = ","
FIELDS = timestamp,transaction_start_time,transaction_end_time,server_host,server_port,client_host,client_port,vlan_id,application_name,ai_sensor_ip_address,ai_sensor_name,ai_sensor_interface_number,application_group,response_code,response_description,query_class,response_query_flag,authoritative_answer_flag,truncation_flag,recursion_desired_flag,recursion_available_flag,reserved_flag,rejected_flag,reverse_lookup_flag,resolved_ip_address,resolved_ttls,tld,subdomain,etld,message,query_type,domain,response_time,query_size,count_of_elements,dns_client_to_server_octets,dns_server_to_client_octets,dns_client_to_server_packets,dns_server_to_client_packets

[netscout_http_header]
DELIMS = ","
FIELDS = timestamp,transaction_start_time,transaction_end_time,server_host,server_port,client_host,client_port,packet_type_name,vlan_id,application_name,ai_sensor_ip_address,ai_sensor_name,ai_sensor_interface_number,message_name,application_group,response_code,response_description,request_host_name,target_uri,user_agent,http_content_type,refferer,uri_path,uri_query_names,uri_query_values,http_client_to_server_octets,http_server_to_client_octets,http_client_to_server_packets,http_server_to_client_packets,http_response_time_usec

[netscout_https_header]
DELIMS = ","
FIELDS = timestamp,transaction_start_time,transaction_end_time,server_host,server_port,client_host,client_port,packet_type_name,vlan_id,application_name,ai_sensor_ip_address,ai_sensor_name,ai_sensor_interface_number,message_name,application_group,response_code,response_description,tls_version,server_name_indicator,cipher,https_response_time,https_client_to_server_octets,https_server_to_client_octets,https_client_to_server_packets,https_server_to_client_packets

[netscout_smb_header]
DELIMS = ","
FIELDS = timestamp,transaction_start_time,transaction_end_time,server_host,server_port,client_host,client_port,packet_type_name,vlan_id,application_name,ai_sensor_ip_address,ai_sensor_name,ai_sensor_interface_number,message_name,application_group,response_code,response_description,authentication_protocol,dialect,file_operation,user_name,tree_name,file_name,smb_response_time,smb_client_to_server_octets,smb_server_to_client_octets,smb_client_to_server_packets,smb_server_to_client_packets

[netscout_icmp_header]
DELIMS = ","
FIELDS = timestamp,transaction_start_time,transaction_end_time,server_host,server_port,client_host,client_port,packet_type_name,vlan_id,application_name,ai_sensor_ip_address,ai_sensor_name,ai_sensor_interface_number,message_name,application_group,response_code,response_description,icmp_client_to_server_octets,icmp_server_to_client_octets,icmp_client_to_server_packets,icmp_server_to_client_packets

[netscout_base_header]
DELIMS = ","
FIELDS = timestamp,flow_start_time,flow_end_time,flow_end_reason_name,server_ip_address,server_port,client_ip_address,client_port,application_name,packet_type_name,vlan_id,ai_sensor_ip_address,ai_sensor_name,ai_sensor_interface_number,application_group,client_to_server_octets,server_to_client_octets,client_to_server_packets,server_to_client_packets
